In [73]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

In [3]:

def load_data_to_mysql(username, password, host, database, file_path, table_name):
    """
    Carrega dados de um arquivo txt para uma tabela no banco de dados MySQL.
    :param username: Nome de usuário para acessar o banco de dados.
    :param password: Senha para acessar o banco de dados.
    :param host: Host onde o banco de dados está hospedado.
    :param database: Nome do banco de dados.
    :param file_path: string com o caminho do arquivo a ser carregado.
    :param table_name: string com o nome da tabela onde os dados serão inseridos.
    """
    engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{database}')

    # Ler o arquivo txt com dados separados por tabulações
    data = pd.read_csv(file_path, sep='\t', encoding='utf-8')

    # Insere os dados na tabela especificada
    data.to_sql(table_name, con=engine, if_exists='append', index=False)

    print(f"Dados importados com sucesso para a tabela {table_name}.")

In [7]:

# Definindo os detalhes do banco de dados
username = "root"
password = "mysqlroot"
host = "127.0.0.1"
database = "loja_muito_bela"

In [26]:
# Caminho do arquivo e nome da tabela
file_path = "Fonte de dados/categoria.txt"
table_name = "categoria"

In [14]:
file_path = "Fonte de dados/cliente.txt"
table_name = "cliente"

In [28]:
file_path = "Fonte de dados/forma_pagamento.txt"
table_name = "forma_pagamento"

In [30]:
file_path = "Fonte de dados/marca.txt"
table_name = "marca"

In [71]:
file_path = "./Fonte de dados/produto.txt"
table_name = "produto"

In [64]:
file_path = "Fonte de dados/produto_variacao.txt"
table_name = "produto_variacao"

In [43]:
file_path = "Fonte de dados/venda_status.txt"
table_name = "venda_status"

In [52]:
file_path = "Fonte de dados/venda.txt"
table_name = "venda"

In [62]:
file_path = "Fonte de dados/venda_item.txt"
table_name = "venda_item"

In [72]:
# Carregando os dados para o banco de dados MySQL
load_data_to_mysql(username, password, host, database, file_path, table_name)

IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'produto_nome' cannot be null")
[SQL: INSERT INTO produto (produto_id, produto_nome, categoria_id, marca_id) VALUES (%(produto_id)s, %(produto_nome)s, %(categoria_id)s, %(marca_id)s)]
[parameters: [{'produto_id': 104, 'produto_nome': '4522 ANYZZIX', 'categoria_id': 107, 'marca_id': 104}, {'produto_id': 105, 'produto_nome': '4522', 'categoria_id': 104, 'marca_id': 104}, {'produto_id': 106, 'produto_nome': 'D', 'categoria_id': 104, 'marca_id': 105}, {'produto_id': 107, 'produto_nome': 'D MAZCALYNI', 'categoria_id': 107, 'marca_id': 105}, {'produto_id': 108, 'produto_nome': 'DIZYRI', 'categoria_id': 104, 'marca_id': 105}, {'produto_id': 109, 'produto_nome': 'DIZYRI MAZCALYNI', 'categoria_id': 107, 'marca_id': 105}, {'produto_id': 110, 'produto_nome': 'DIZYRI MAZCALYNI', 'categoria_id': 107, 'marca_id': 105}, {'produto_id': 111, 'produto_nome': 'DANHYLL IDYTYIN', 'categoria_id': 104, 'marca_id': 105}  ... displaying 10 of 8480 total bound parameter sets ...  {'produto_id': 8701, 'produto_nome': 'PIADRYIR DINTILLI', 'categoria_id': 105, 'marca_id': 116}, {'produto_id': 8702, 'produto_nome': 'TIYNT YNNICINCI - TIYNT CIMPACT FRAYZ NATARIL IT LAMYNIAX ZPF 20', 'categoria_id': 105, 'marca_id': 118}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)